"""Create formality indicator plots for ZASCA and EMICRON data."""

import altair as alt
import pandas as pd


def plot_formality_by_indicator(df_plot: pd.DataFrame) -> alt.VConcatChart:
    """Create separate butterfly charts for each formality indicator.

    Args:
        df_plot: the dataframe generated by the 'formality' function with common/excess structure.

    Returns:
        alt.VConcatChart: Separate butterfly plots for each indicator.

    """
    color_scale = alt.Scale(
        domain=["ZASCA_common", "ZASCA_ZASCA", "EMICRON_common", "EMICRON_EMICRON"],
        range=["#00B2A2", "#66D1C7", "#FF5836", "#FFAC9B"],
    )

    charts = []
    indicators = ["Registro RUT", "Contabilidad", "Acceso a Crédito"]

    for indicator in indicators:
        indicator_data = df_plot.loc[df_plot["indicator"] == indicator].copy()

        # determine sort order
        if indicator in {"Registro RUT", "Acceso a Crédito"}:
            category_sort = ["Sí", "No"]
        elif indicator == "Contabilidad":
            category_sort = [
                "No lleva registros",
                "Cuentas en la cabeza",
                "Registros informales",
                "Libros contables formales",
                "Excel/Software",
            ]
        else:
            category_sort = None

        # create bars
        chart = (
            alt.Chart(indicator_data)
            .mark_bar()
            .encode(
                y=alt.Y(
                    "category:N",
                    axis=alt.Axis(labels=True, title="", grid=False, ticks=False, domain=False, labelFontSize=10),
                    sort=category_sort,
                ),
                x=alt.X(
                    "plot_value:Q",
                    axis=alt.Axis(labels=False, title=None, grid=False, ticks=False, domain=False),
                ),
                color=alt.Color("color_category:N", scale=color_scale, legend=None),
                order=alt.Order("type:N", sort="descending"),
            )
        )

        # calculate total values for each source per category
        df_totals = indicator_data.groupby(["category", "source"])["plot_value"].sum().reset_index()
        df_totals["abs_value"] = df_totals["plot_value"].abs()
        # use larger offset for RUT/Credit (shorter bars), smaller for Contabilidad
        offset_multiplier = 4 if indicator in {"Registro RUT", "Acceso a Crédito"} else 2.5
        df_totals["x_offset"] = df_totals["plot_value"] + offset_multiplier * df_totals["plot_value"].apply(
            lambda x: -1 if x < 0 else 1
        )
        df_totals["text_label"] = df_totals["abs_value"].round(0).astype(int).astype(str) + "%"

        # add text labels showing total percentages
        text_chart = (
            alt.Chart(df_totals)
            .mark_text(align="center", baseline="middle", fontSize=10, color="black")
            .encode(
                y=alt.Y("category:N", sort=category_sort),
                x=alt.X("x_offset:Q"),
                text=alt.Text("text_label:N"),
            )
        )

        # determine height based on indicator
        height = 200 if indicator == "Contabilidad" else 70

        combined_chart = (chart + text_chart).properties(
            width=500,
            height=height,
            title=alt.TitleParams(text=indicator, fontSize=12),
        )

        charts.append(combined_chart)

    return alt.vconcat(*charts, spacing=15).configure_view(strokeWidth=0)
